const exampleData = [
  {
    id: 92,
    restaurant_id: 1036,
    username: 'pAtY',
    date: '2018-06-05T04:11:05.950Z',
    overall_rating: 4,
    food_rating: 1,
    service_rating: 3,
    ambiance_rating: 3,
    value_rating: 3,
    noise_level: 1,
    recommended: 1,
    body: 'Lorem ipsum dolor sit amet, pri id vide homero alienum, nibh nusquam mel no. Pro perfecto atomorum sapientem cu, elit natum ex eum. Est probo qualisque ut. Quo at congue iriure.' },
  {
    id: 93,
    restaurant_id: 1048,
    username: 'WhO7',
    date: '2018-06-05T04:11:05.950Z',
    overall_rating: 3,
    food_rating: 2,
    service_rating: 2,
    ambiance_rating: 1,
    value_rating: 3,
    noise_level: 3,
    recommended: 1,
    body: 'Lorem ipsum dolor sit amet, pri id vide homero alienum, nibh nusquam mel no. Pro perfecto atomorum sapientem cu, elit natum ex eum. Est probo qualisque ut. Quo at congue iriure.' },
  {
    id: 94,
    restaurant_id: 1023,
    username: 'QtfW',
    date: '2018-06-05T04:11:05.950Z',
    overall_rating: 2,
    food_rating: 1,
    service_rating: 2,
    ambiance_rating: 4,
    value_rating: 1,
    noise_level: 2,
    recommended: 1,
    body: 'Lorem ipsum dolor sit amet, pri id vide homero alienum, nibh nusquam mel no. Pro perfecto atomorum sapientem cu, elit natum ex eum. Est probo qualisque ut. Quo at congue iriure.' },
  {
    id: 95,
    restaurant_id: 1059,
    username: 'ivBQ',
    date: '2018-06-05T04:11:05.950Z',
    overall_rating: 2,
    food_rating: 4,
    service_rating: 2,
    ambiance_rating: 2,
    value_rating: 1,
    noise_level: 1,
    recommended: 1,
    body: 'Lorem ipsum dolor sit amet, pri id vide homero alienum, nibh nusquam mel no. Pro perfecto atomorum sapientem cu, elit natum ex eum. Est probo qualisque ut. Quo at congue iriure.' },
  {
    id: 96,
    restaurant_id: 1099,
    username: 'ThRb',
    date: '2018-06-05T04:11:05.950Z',
    overall_rating: 2,
    food_rating: 4,
    service_rating: 2,
    ambiance_rating: 2,
    value_rating: 1,
    noise_level: 1,
    recommended: 1,
    body: 'Lorem ipsum dolor sit amet, pri id vide homero alienum, nibh nusquam mel no. Pro perfecto atomorum sapientem cu, elit natum ex eum. Est probo qualisque ut. Quo at congue iriure.' },
  {
    id: 97,
    restaurant_id: 1033,
    username: 'O7zU',
    date: '2018-06-05T04:11:05.950Z',
    overall_rating: 2,
    food_rating: 2,
    service_rating: 1,
    ambiance_rating: 4,
    value_rating: 4,
    noise_level: 3,
    recommended: 1,
    body: 'Lorem ipsum dolor sit amet, pri id vide homero alienum, nibh nusquam mel no. Pro perfecto atomorum sapientem cu, elit natum ex eum. Est probo qualisque ut. Quo at congue iriure.' },
  {
    id: 98,
    restaurant_id: 1012,
    username: 'DVnT',
    date: '2018-06-05T04:11:05.950Z',
    overall_rating: 1,
    food_rating: 1,
    service_rating: 4,
    ambiance_rating: 2,
    value_rating: 3,
    noise_level: 1,
    recommended: 0,
    body: 'Lorem ipsum dolor sit amet, pri id vide homero alienum, nibh nusquam mel no. Pro perfecto atomorum sapientem cu, elit natum ex eum. Est probo qualisque ut. Quo at congue iriure.' },
  {
    id: 99,
    restaurant_id: 1073,
    username: 'm5rm',
    date: '2018-06-05T04:11:05.950Z',
    overall_rating: 3,
    food_rating: 3,
    service_rating: 2,
    ambiance_rating: 2,
    value_rating: 1,
    noise_level: 2,
    recommended: 1,
    body: 'Lorem ipsum dolor sit amet, pri id vide homero alienum, nibh nusquam mel no. Pro perfecto atomorum sapientem cu, elit natum ex eum. Est probo qualisque ut. Quo at congue iriure.' },
  {
    id: 100,
    restaurant_id: 1065,
    username: 'hyEm',
    date: '2018-06-05T17:27:52.645Z',
    overall_rating: 3,
    food_rating: 4,
    service_rating: 1,
    ambiance_rating: 4,
    value_rating: 4,
    noise_level: 2,
    recommended: 0,
    body: 'Lorem ipsum dolor sit amet, pri id vide homero alienum, nibh nusquam mel no. Pro perfecto atomorum sapientem cu, elit natum ex eum. Est probo qualisque ut. Quo at congue iriure.' }
];

export default exampleData;